"use client"
import React,{useEffect,useState}from'react'
import{getAvailableThemes,getTheme,getAppearance,getUiScaleMode,setTheme,setAppearance,setUiScaleMode,type ThemeName,type AppearanceMode,type UiScaleMode}from'@/lib/utils/theme'
import{X,Sliders,Palette,Monitor,RotateCcw,Wifi,Gauge,Check,Sun,Moon,Laptop}from'lucide-react'
import{AnimatePresence,motion}from'framer-motion'
type Props={open:boolean;onClose:()=>void;loading:boolean;error:string|null;stationsCount:number;setQuery:(v:string)=>void;filters:any;toggleOnlyFavs:(v:boolean)=>void;onResetFilters:()=>void}
const scales:Array<{key:UiScaleMode;label:string}>=[{key:'small',label:'Compacto'},{key:'medium',label:'Estándar'},{key:'large',label:'Amplio'}]
const colors:Record<ThemeName,{label:string;color:string}>={amoled:{label:'Rojo',color:'#ef4444'},gold:{label:'Dorado',color:'#d4af37'},purple:{label:'Morado',color:'#a855f7'},white:{label:'Plata',color:'#fff'},'wear-ocean':{label:'Océano',color:'#06b6d4'},'wear-sunset':{label:'Naranja',color:'#f97316'},'wear-galaxy':{label:'Azul',color:'#3b82f6'},'wear-mint':{label:'Verde',color:'#10b981'},'wear-cherry':{label:'Rosa',color:'#f43f5e'}}
export default function SideMenu({open,onClose,onResetFilters}:Props){const themes=getAvailableThemes();const[currentTheme,setCurrentTheme]=useState<ThemeName>('wear-mint');const[appearance,setAppearanceState]=useState<AppearanceMode>('dark');const[scale,setScale]=useState<UiScaleMode>('auto');useEffect(()=>{setCurrentTheme(getTheme());setAppearanceState(getAppearance());setScale(getUiScaleMode())},[open]);const appearanceOptions=[{key:'dark' as AppearanceMode,label:'Oscuro AMOLED',desc:'Negro puro',icon:Moon},{key:'light' as AppearanceMode,label:'Claro / Exterior',desc:'Máxima visibilidad',icon:Sun},{key:'system' as AppearanceMode,label:'Automático',desc:'Según dispositivo',icon:Laptop}];const effective=scale==='auto'||scale==='xlarge'?'medium':scale;return <AnimatePresence>{open&&<div className="fixed inset-0 z-50 flex justify-end"><motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 bg-black/70 backdrop-blur-sm" onClick={onClose}/><motion.aside initial={{x:'100%'}} animate={{x:0}} exit={{x:'100%'}} transition={{type:'spring',damping:28,stiffness:260}} className="relative z-10 w-full sm:w-[400px] h-full bg-black border-l border-white/[0.09] shadow-2xl flex flex-col text-zinc-100"><header className="flex items-center justify-between px-5 py-4 border-b border-white/[0.08]"><div className="flex items-center gap-3"><div className="w-9 h-9 rounded-xl grid place-items-center border" style={{background:'var(--accent-subtle)',borderColor:'var(--accent-glow)',color:'var(--accent)'}}><Sliders size={17}/></div><div><h2 className="font-bold text-white">Ajustes</h2><p className="text-xs text-zinc-500">Personaliza tu experiencia</p></div></div><button onClick={onClose} className="w-9 h-9 rounded-full grid place-items-center text-zinc-500 hover:text-white"><X size={19}/></button></header><div className="flex-1 overflow-y-auto px-5 py-5 space-y-7">
<section><div className="flex items-center gap-2 mb-3"><Sun size={14} style={{color:'var(--accent)'}}/><h3 className="text-xs font-bold uppercase tracking-wider text-zinc-300">Apariencia</h3></div><div className="grid gap-2">{appearanceOptions.map(o=>{const I=o.icon,s=appearance===o.key;return <button key={o.key} onClick={()=>{setAppearance(o.key);setAppearanceState(o.key)}} className="flex items-center gap-3 p-3 rounded-xl border text-left" style={s?{borderColor:'var(--accent)',background:'var(--accent-subtle)'}:{borderColor:'var(--border-glass)',background:'var(--bg-glass)'}}><I size={18} style={s?{color:'var(--accent)'}:undefined}/><span className="flex-1"><b className="block text-sm">{o.label}</b><small className="text-zinc-500">{o.desc}</small></span>{s&&<Check size={16} style={{color:'var(--accent)'}}/>}</button>})}</div></section>
<section><div className="flex items-center gap-2 mb-3"><Palette size={14} style={{color:'var(--accent)'}}/><h3 className="text-xs font-bold uppercase tracking-wider text-zinc-300">Color de acento</h3></div><div className="rounded-2xl border border-white/[0.07] bg-white/[0.025] p-4"><div className="flex flex-wrap gap-3">{themes.map(t=>{const i=colors[t],s=currentTheme===t;return <button key={t} onClick={()=>{setTheme(t);setCurrentTheme(t)}} title={i.label} className="w-10 h-10 rounded-full grid place-items-center border-2" style={{background:i.color,borderColor:s?'currentColor':'transparent',boxShadow:s?`0 0 0 3px ${i.color}35`:'none'}}>{s&&<Check size={16} className={t==='white'?'text-black':'text-white'}/>}</button>})}</div><p className="mt-3 text-xs text-zinc-500">El color se aplica a botones, estados y elementos activos.</p></div></section>
<section><div className="flex items-center gap-2 mb-3"><Monitor size={14} style={{color:'var(--accent)'}}/><h3 className="text-xs font-bold uppercase tracking-wider text-zinc-300">Interfaz</h3></div><div className="grid grid-cols-3 gap-2 p-1.5 rounded-2xl bg-zinc-950 border border-white/[0.07]">{scales.map(o=><button key={o.key} onClick={()=>{setUiScaleMode(o.key);setScale(o.key)}} className="h-10 rounded-xl text-xs font-semibold" style={effective===o.key?{background:'var(--accent-subtle)',color:'var(--accent)',border:'1px solid var(--accent-glow)'}:{color:'var(--text-muted)'}}>{o.label}</button>)}</div></section>
<section><div className="flex items-center gap-2 mb-3"><Wifi size={14} style={{color:'var(--accent)'}}/><h3 className="text-xs font-bold uppercase tracking-wider text-zinc-300">Reproducción</h3></div><div className="rounded-2xl border border-white/[0.07] bg-white/[0.025] divide-y divide-white/[0.06]"><div className="p-4 flex justify-between"><div><p className="text-sm font-semibold">Reconexión automática</p><p className="text-xs text-zinc-500">Recupera el audio si la señal se corta.</p></div><span className="text-[10px] font-bold" style={{color:'var(--accent)'}}>ACTIVA</span></div><div className="p-4 flex justify-between"><div><p className="text-sm font-semibold">Audio de baja latencia</p><p className="text-xs text-zinc-500">Optimizado para radio en directo.</p></div><Gauge size={18}/></div></div></section><button onClick={onResetFilters} className="w-full h-11 rounded-xl flex items-center justify-center gap-2 text-xs border border-white/[0.07]"><RotateCcw size={14}/> Restablecer filtros</button></div><div className="sm:hidden p-4 border-t border-white/[0.08]"><button onClick={onClose} className="w-full h-12 rounded-xl text-sm font-bold text-black" style={{background:'var(--accent)'}}>Listo</button></div></motion.aside></div>}</AnimatePresence>}
