create table if not exists public.global_stations (
  id bigint generated by default as identity primary key,
  name text not null,
  url text not null,
  country text not null,
  region text not null,
  district text,
  caserio text,
  status text not null default 'pending',
  reviewed_by text,
  approved_at timestamptz,
  created_at timestamptz not null default now()
);

create unique index if not exists global_stations_unique_normalized
  on public.global_stations (lower(trim(name)), lower(trim(url)));

alter table public.global_stations enable row level security;

update public.global_stations
set status = 'approved'
where status is null;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'global_stations_name_len') then
    alter table public.global_stations
      add constraint global_stations_name_len check (char_length(trim(name)) between 2 and 120);
  end if;

  if not exists (select 1 from pg_constraint where conname = 'global_stations_country_len') then
    alter table public.global_stations
      add constraint global_stations_country_len check (char_length(trim(country)) between 2 and 80);
  end if;

  if not exists (select 1 from pg_constraint where conname = 'global_stations_region_len') then
    alter table public.global_stations
      add constraint global_stations_region_len check (char_length(trim(region)) between 2 and 80);
  end if;

  if not exists (select 1 from pg_constraint where conname = 'global_stations_valid_url') then
    alter table public.global_stations
      add constraint global_stations_valid_url check (
        lower(url) ~ '^(https?:\/\/)' and
        lower(url) !~ '^(https?:\/\/)(localhost|127\.0\.0\.1|::1)'
      );
  end if;

  if not exists (select 1 from pg_constraint where conname = 'global_stations_status_check') then
    alter table public.global_stations
      add constraint global_stations_status_check check (status in ('pending', 'approved', 'rejected'));
  end if;
end;
$$;

create or replace function public.enforce_global_stations_rate_limit()
returns trigger
language plpgsql
as $$
declare
  last_minute_count integer;
begin
  select count(*)
  into last_minute_count
  from public.global_stations
  where created_at >= (now() - interval '1 minute');

  if last_minute_count >= 60 then
    raise exception 'Rate limit global activo. Intenta nuevamente en unos segundos.';
  end if;

  new.status := 'pending';
  new.reviewed_by := null;
  new.approved_at := null;
  return new;
end;
$$;

drop trigger if exists trg_global_stations_rate_limit on public.global_stations;
create trigger trg_global_stations_rate_limit
before insert on public.global_stations
for each row
execute function public.enforce_global_stations_rate_limit();

drop policy if exists "read approved global stations" on public.global_stations;
create policy "read approved global stations"
on public.global_stations
for select
to anon, authenticated
using (status = 'approved');

drop policy if exists "insert pending global stations" on public.global_stations;
create policy "insert pending global stations"
on public.global_stations
for insert
to anon, authenticated
with check (status = 'pending');
